Base directory can be specified now.

diff --git a/ergrep b/ergrep
--- a/ergrep
+++ b/ergrep
@@ -1,14 +1,14 @@
 #!/bin/sh
 
-USAGE="
-$(basename $0): recursive grep in Erlang source files.
-  Usage: $(basename $0) [-v|--verbose] [-q|--quiet] [-i|--insensitive] <Expression to be found in files>
+usage="
+$(basename $0): recursive grep in Erlang source files, either from TARGET_BASE_DIR, if specified, otherwise from the current directory.
+  Usage: $(basename $0) [-v|--verbose] [-q|--quiet] [-i|--insensitive] <Expression to be found in files> [TARGET_BASE_DIR]
   Options:
 	-v or --verbose: be specifically verbose
 	-q or --quiet: be specifically quiet, just listing matches
 	-f or --filenames-only: display only filenames, not also the matched patterns, and if there are multiple matches in the same file, its filename will be output only once (implies quiet)
 	-i or --insensitive: perform case-insensitive searches in the content of files, and also in the searched Erlang filenames
-  Example: $(basename $0) -i 'list_to_form('"
+  Example: $(basename $0) -i 'list_to_form(' /tmp"
 
 
 find=$(which find | grep -v ridiculously 2>/dev/null)
@@ -18,13 +18,13 @@ grep=$(which grep | grep -v ridiculously 2>/dev/null)
 #echo "find = ${find}"
 
 
-if [ ! -x "${grep}" ] ; then
+if [ ! -x "${grep}" ]; then
 	echo "Error, no executable grep found." 1>&2
 	exit 5
 fi
 
 
-if [ ! -x "${find}" ] ; then
+if [ ! -x "${find}" ]; then
 	echo "Error, no executable find found." 1>&2
 	exit 6
 fi
@@ -42,18 +42,18 @@ filenames_only=1
 # Done to force grep to display the filename (otherwise it will not)
 # No need to create it, however.
 #
-force_multi_files="$HOME/.ergrep.toDelete.tmp"
+force_multi_files="$HOME/.ergrep.to-delete.tmp"
 
 name_opt="-name"
 
-if [ $# -eq 0 ] ; then
-	echo "Error, too few parameters. $USAGE" 1>&2
+if [ $# -eq 0 ]; then
+	echo "Error, too few parameters. ${usage}" 1>&2
 	exit 1
 fi
 
 
-if [ $# -ge 4 ] ; then
-	echo "Error, too many parameters ($*). $USAGE" 1>&2
+if [ $# -ge 4 ]; then
+	echo "Error, too many parameters ($*). ${usage}" 1>&2
 	exit 2
 fi
 
@@ -63,14 +63,14 @@ fi
 
 token_eaten=0
 
-while [ $token_eaten -eq 0 ] ; do
+while [ ${token_eaten} -eq 0 ]; do
 
 	read_parameter="$1"
-	#echo "read_parameter = $read_parameter"
+	#echo "read_parameter = ${read_parameter}"
 
 	token_eaten=1
 
-	if [ "$read_parameter" = "--verbose" -o "$read_parameter" = "-v" ] ; then
+	if [ "${read_parameter}" = "--verbose" -o "${read_parameter}" = "-v" ]; then
 		verbose=0
 		quiet=1
 		echo "Verbose mode activated."
@@ -78,50 +78,73 @@ while [ $token_eaten -eq 0 ] ; do
 	fi
 
 
-	if [ "$read_parameter" = "--quiet" -o "$read_parameter" = "-q" ] ; then
+	if [ "${read_parameter}" = "--quiet" -o "${read_parameter}" = "-q" ]; then
 		verbose=1
 		quiet=0
 		#echo "Quiet mode activated."
 		token_eaten=0
 	fi
 
-	if [ "$read_parameter" = "--filenames-only" -o "$read_parameter" = "-f" ] ; then
+	if [ "${read_parameter}" = "--filenames-only" -o "${read_parameter}" = "-f" ]; then
 		verbose=1
 		quiet=0
 		filenames_only=0
-		[ $quiet -eq 0 ] || echo "Only filenames will be written, not found patterns."
+		[ ${quiet} -eq 0 ] || echo "Only filenames will be written, not found patterns."
 		token_eaten=0
 	fi
 
 
-	if [ "$read_parameter" = "--insensitive" -o "$read_parameter" = "-i" ] ;
+	if [ "${read_parameter}" = "--insensitive" -o "${read_parameter}" = "-i" ];
 	then
 		insensitive_opt="-i"
 		name_opt="-iname"
-		[ $quiet -eq 0 ] || echo "Case-insensitive mode activated."
+		[ ${quiet} -eq 0 ] || echo "Case-insensitive mode activated."
 		token_eaten=0
 	fi
 
-	if [ -n "$read_parameter" ] ; then
+	if [ -n "${read_parameter}" ]; then
 		shift
 	fi
 
 done
 
-if [ -z "$read_parameter" ] ; then
-	echo "Error, too few parameters. $USAGE" 1>&2
+if [ -z "${read_parameter}" ]; then
+	echo "Error, too few parameters. ${usage}" 1>&2
 	exit 3
 fi
 
 
-searched_expression="$read_parameter"
+target_base_dir="$1"
+
+if [ -z "${target_base_dir}" ]; then
+	target_base_dir="$(realpath .)"
+	[ ${verbose} -eq 0 ] || echo "Proceeding from current directory ('${target_base_dir}')."
+
+else
+	target_base_dir=$(realpath "${target_base_dir}")
+	[ ${verbose} -eq 0 ] || echo "Proceeding from specified directory ('${target_base_dir}')."
+	shift
+fi
+
+if [ ! -d "${target_base_dir}" ]; then
+
+	echo "  Error, target base directory ('${target_base_dir}') does not exist." 1>&2
+
+	exit 10
+
+fi
+
+#echo "target_base_dir = ${target_base_dir}"
+
+
+searched_expression="${read_parameter}"
 #echo "searched_expression = $searched_expression"
 
 
 # Then check no parameter remains:
 
-if [ $# -ge 1 ] ; then
-	echo "Error, too many parameters ($*). $USAGE" 1>&2
+if [ $# -ge 1 ]; then
+	echo "Error, too many parameters (remaining: '$*'). ${usage}" 1>&2
 	exit 4
 fi
 
@@ -134,30 +157,30 @@ filter_erl='*.?rl'
 # Unable to properly define a correctly-protected variable:
 #filter_expr="${name_opt} ${filter_erl}"
 
-if [ $verbose -eq 0 ] ; then
+if [ ${verbose} -eq 0 ]; then
 
-	#echo "Will search in following files based on: $find . ${filter_expr}:"
-	echo "Will search in following files based on: $find . ${name_opt} ${filter_erl}:"
-	$find . ${name_opt} "${filter_erl}"
+	#echo "Will search in following files from '${target_base_dir}' based on: ${find} . ${filter_expr}:"
+	echo "Will search in following files from '${target_base_dir}' based on: ${find} . ${name_opt} ${filter_erl}:"
+	${find} . ${name_opt} "${filter_erl}"
 
 fi
 
 
 
-[ $quiet -eq 0 ] || echo "
-	Recursive grep for expression <${searched_expression}> in all Erlang files:
+[ ${quiet} -eq 0 ] || echo "
+	Recursive grep for expression <${searched_expression}> in all Erlang files from '${target_base_dir}':
 	"
 
-if [ $filenames_only -eq 1 ] ; then
+if [ ${filenames_only} -eq 1 ]; then
 
 	# Most usual case:
-	$find . ${name_opt} "${filter_erl}" -exec $grep ${base_grep_opt} ${insensitive_opt} "${searched_expression}" '{}' $force_multi_files ';' 2>/dev/null
+	${find} "${target_base_dir}" ${name_opt} "${filter_erl}" -exec ${grep} ${base_grep_opt} ${insensitive_opt} "${searched_expression}" '{}' ${force_multi_files} ';' 2>/dev/null
 
 else
 
-	$find . ${name_opt} "${filter_erl}" -exec $grep ${base_grep_opt} ${insensitive_opt} "${searched_expression}" '{}' $force_multi_files ';' 2>/dev/null | sed 's|:.*$||1' | uniq
+	${find} "${target_base_dir}" ${name_opt} "${filter_erl}" -exec ${grep} ${base_grep_opt} ${insensitive_opt} "${searched_expression}" '{}' ${force_multi_files} ';' 2>/dev/null | sed 's|:.*$||1' | uniq
 
 fi
 
-[ $quiet -eq 0 ] || echo "
+[ ${quiet} -eq 0 ] || echo "
 End of search."
