Emacs client better managed. More file types managed.

diff --git a/n b/n
--- a/n
+++ b/n
@@ -144,10 +144,43 @@ chooseEmacs()
 		ALTERNATE_EDITOR="/bin/emacs --geometry=83x60"
 
 		if [ $standalone -eq 1 ] ; then
+
+			EMACS_CLIENT="/bin/emacsclient"
+
+			if [ ! -x "${EMACS_CLIENT}" ] ; then
+
+				EMACS_CLIENT="/usr/bin/emacsclient"
+
+				if [ ! -x "${EMACS_CLIENT}" ] ; then
+
+					echo " Error, no emacs client available." 1>&2
+					exit 55
+
+				fi
+
+			fi
+
 			# Default:
-			EDITOR="/bin/emacsclient --alternate-editor=emacs"
+			EDITOR="${EMACS_CLIENT} --alternate-editor=emacs"
+
 		else
+
+			EMACS="/bin/emacs"
+
+			if [ ! -x "${EMACS}" ] ; then
+
+				EMACS="/usr/bin/emacs"
+
+				if [ ! -x "${EMACS}" ] ; then
+
+					echo " Error, no (standalone) emacs available." 1>&2
+					exit 56
+
+				fi
+			fi
+
 			EDITOR="/bin/emacs"
+
 		fi
 
 		VISUAL=$EDITOR
@@ -292,6 +325,10 @@ autoSelectEditor()
 
 applyEditor()
 {
+
+	#echo "MULTI_WIN = ${MULTI_WIN}"
+	#echo "EDITOR_SHORT_NAME = ${EDITOR_SHORT_NAME}"
+	#echo "EDITOR = ${EDITOR}"
 
 	# Let's hope the display is OK.
 
@@ -528,7 +565,7 @@ if [ $do_find -eq 0 ] ; then
 	target_file=$(echo "${PARAMETERS}" | sed 's|^ ||1' | sed 's|:.*$||1')
 	#echo "target_file = $target_file"
 
-	target_path=$(/bin/find . -name $target_file)
+	target_path=$(find . -name $target_file)
 
 	if [ -z "${target_path}" ] ; then
 
@@ -650,6 +687,47 @@ if [ "${EXTENSION}" = "dia" ] ; then
 
 	EDITOR=$(which dia)
 	EDITOR_SHORT_NAME="dia"
+	applyEditor
+	exit 0
+
+fi
+
+
+if [ "${EXTENSION}" = "xlsx" ] ; then
+
+	EDITOR=$(which libreoffice)
+	EDITOR_SHORT_NAME="LibreOffice"
+	applyEditor
+	exit 0
+
+fi
+
+
+if [ "${EXTENSION}" = "docx" ] ; then
+
+	EDITOR=$(which libreoffice)
+	EDITOR_SHORT_NAME="LibreOffice"
+	applyEditor
+	exit 0
+
+fi
+
+
+if [ "${EXTENSION}" = "traces" ] ; then
+
+	LOGMX=$(which logmx.sh)
+
+	if [ ! -x "${LOGMX}" ] ; then
+
+		echo "  (no LogMX found, using default editor for traces)"
+
+	else
+
+		EDITOR="${LOGMX}"
+		EDITOR_SHORT_NAME="LogMX"
+
+	fi
+
 	applyEditor
 	exit 0
 
