Style updated.

diff --git a/regrep b/regrep
--- a/regrep
+++ b/regrep
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-usage="  $(basename $0): recursive grep for the ones that lack it.
+usage="$(basename $0): recursive grep for the ones that lack it.
 
   Usage: $(basename $0) [-v|--verbose] [-q|--quiet] [-i|--insensitive] [-r|--restructured] <Expression to be found in files> [<Filter on files>]
 
@@ -14,21 +14,21 @@ usage="  $(basename $0): recursive grep for the ones that lack it.
   Example: $(basename $0) -i 'little red rooster' '*.txt'"
 
 
-find=$(which find | grep -v ridiculously 2>/dev/null)
-grep=$(which grep | grep -v ridiculously 2>/dev/null)
+find="$(which find 2>/dev/null)"
+grep="$(which grep 2>/dev/null)"
 
 #echo "grep = ${grep}"
 #echo "find = ${find}"
 
 
 if [ ! -x "${grep}" ]; then
-	echo "Error, no executable grep found." 1>&2
+	echo "  Error, no executable 'grep' found." 1>&2
 	exit 5
 fi
 
 
 if [ ! -x "${find}" ]; then
-	echo "Error, no executable find found." 1>&2
+	echo   "Error, no executable 'find' found." 1>&2
 	exit 6
 fi
 
@@ -46,7 +46,7 @@ filenames_only=1
 # Done to force grep to display the filename (otherwise it will not)
 # No need to create it, however.
 #
-force_multi_files="$HOME/.regrep.toDelete.tmp"
+force_multi_files="${HOME}/.$(basename $0).to-delete.tmp"
 
 name_opt="-name"
 
@@ -58,13 +58,15 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 fi
 
 if [ $# -eq 0 ]; then
-	echo "Error, too few parameters. ${usage}" 1>&2
+	echo "Error, too few parameters.
+${usage}" 1>&2
 	exit 1
 fi
 
 
 if [ $# -ge 7 ]; then
-	echo "Error, too many parameters ($*). ${usage}" 1>&2
+	echo "Error, too many parameters ($*).
+${usage}" 1>&2
 	exit 2
 fi
 
@@ -77,11 +79,11 @@ token_eaten=0
 while [ $token_eaten -eq 0 ]; do
 
 	read_parameter="$1"
-	#echo "read_parameter = $read_parameter"
+	#echo "read_parameter = ${read_parameter}"
 
 	token_eaten=1
 
-	if [ "$read_parameter" = "--verbose" -o "$read_parameter" = "-v" ]; then
+	if [ "${read_parameter}" = "--verbose" ] || [ "${read_parameter}" = "-v" ]; then
 		verbose=0
 		quiet=1
 		echo "Verbose mode activated."
@@ -89,14 +91,14 @@ while [ $token_eaten -eq 0 ]; do
 	fi
 
 
-	if [ "$read_parameter" = "--quiet" -o "$read_parameter" = "-q" ]; then
+	if [ "${read_parameter}" = "--quiet" ] || [ "${read_parameter}" = "-q" ]; then
 		verbose=1
 		quiet=0
 		#echo "Quiet mode activated."
 		token_eaten=0
 	fi
 
-	if [ "$read_parameter" = "--filenames-only" -o "$read_parameter" = "-f" ]; then
+	if [ "${read_parameter}" = "--filenames-only" ] || [ "${read_parameter}" = "-f" ]; then
 		verbose=1
 		quiet=0
 		filenames_only=0
@@ -105,7 +107,7 @@ while [ $token_eaten -eq 0 ]; do
 	fi
 
 
-	if [ "$read_parameter" = "--insensitive" -o "$read_parameter" = "-i" ];
+	if [ "${read_parameter}" = "--insensitive" ] || [ "${read_parameter}" = "-i" ];
 	then
 		insensitive_opt="-i"
 		name_opt="-iname"
@@ -114,7 +116,7 @@ while [ $token_eaten -eq 0 ]; do
 	fi
 
 
-	if [ "$read_parameter" = "--restructured" -o "$read_parameter" = "-r" ];
+	if [ "${read_parameter}" = "--restructured" ] || [ "${read_parameter}" = "-r" ];
 	then
 		restructured_mode=0
 		[ $quiet -eq 0 ] || echo "ReStructured text mode activated."
@@ -122,7 +124,7 @@ while [ $token_eaten -eq 0 ]; do
 	fi
 
 
-	if [ -n "$read_parameter" ]; then
+	if [ -n "${read_parameter}" ]; then
 		shift
 	fi
 
@@ -131,22 +133,24 @@ done
 
 # Then check one or two parameters remain indeed:
 
-if [ -z "$read_parameter" ]; then
-	echo "Error, too few parameters. ${usage}" 1>&2
+if [ -z "${read_parameter}" ]; then
+	echo "Error, too few parameters.
+${usage}" 1>&2
 	exit 3
 fi
 
 
 if [ $# -ge 2 ]; then
-	echo "Error, too many parameters ($*). ${usage}" 1>&2
+	echo "Error, too many parameters ($*).
+${usage}" 1>&2
 	exit 4
 fi
 
 
 base_grep_opt="--color"
 
-searched_expression="$read_parameter"
-#echo "searched_expression = $searched_expression"
+searched_expression="${read_parameter}"
+#echo "searched_expression = ${searched_expression}"
 
 filter_on_file="$1"
 #echo "filter_on_file = $filter_on_file"
@@ -156,9 +160,9 @@ if [ $verbose -eq 0 ]; then
 
 	echo "Will search in following files:"
 	if [ -z "$filter_on_file" ]; then
-		$find . -exec /bin/ls '{}' ';' 2>/dev/null
+		"${find}" . -exec /bin/ls '{}' ';' 2>/dev/null
 	else
-		$find . -exec /bin/ls '{}' $force_multi_files ';' 2>/dev/null
+		"${find}" . -exec /bin/ls '{}' "${force_multi_files}" ';' 2>/dev/null
 	fi
 
 fi
@@ -167,42 +171,42 @@ fi
 if [ -z "$filter_on_file" ]; then
 
 	[ $quiet -eq 0 ] || echo "
-	Recursive grep for expression <$searched_expression> in all files:
+	Recursive grep for expression <${searched_expression}> in all files:
 	"
 
 	if [ $restructured_mode -eq 1 ]; then
 
 		if [ $filenames_only -eq 1 ]; then
 
-			$find . -exec $grep ${base_grep_opt} ${insensitive_opt} "$searched_expression" '{}' $force_multi_files ';' 2>/dev/null
+			"${find}" . -exec "${grep}" ${base_grep_opt} ${insensitive_opt} "${searched_expression}" '{}' "${force_multi_files}" ';' 2>/dev/null
 
 		else
 
-			$find . -exec $grep ${base_grep_opt} ${insensitive_opt} "$searched_expression" '{}' $force_multi_files ';' 2>/dev/null | sed 's|:.*$||1' | uniq
+			"${find}" . -exec "${grep}" ${base_grep_opt} ${insensitive_opt} "${searched_expression}" '{}' "${force_multi_files}" ';' 2>/dev/null | sed 's|:.*$||1' | uniq
 
 		fi
 
 	else
 
 		# No filter specified, using '*.rst':
-		$find . -name tmp-rst -prune -o ${name_opt} '*.rst' -exec $grep ${base_grep_opt} ${insensitive_opt} "$searched_expression" '{}' $force_multi_files ';' 2>/dev/null
+		"${find}" . -name tmp-rst -prune -o ${name_opt} '*.rst' -exec "${grep}" ${base_grep_opt} ${insensitive_opt} "${searched_expression}" '{}' "${force_multi_files}" ';' 2>/dev/null
 
 	fi
 
 else
 
 	[ $quiet -eq 0 ] || echo "
-	Recursive grep for expression <$searched_expression> in all files matching <$filter_on_file>:
+	Recursive grep for expression <${searched_expression}> in all files matching <$filter_on_file>:
 	"
 
 	if [ $restructured_mode -eq 1 ]; then
 
 		if [ $filenames_only -eq 1 ]; then
 
-			$find . ${name_opt} "$filter_on_file" -exec $grep ${base_grep_opt} ${insensitive_opt} "$searched_expression" '{}' $force_multi_files ';' 2>/dev/null
+			"${find}" . ${name_opt} "$filter_on_file" -exec "${grep}" ${base_grep_opt} ${insensitive_opt} "${searched_expression}" '{}' "${force_multi_files}" ';' 2>/dev/null
 
 		else
-			$find . ${name_opt} "$filter_on_file" -exec $grep ${base_grep_opt} ${insensitive_opt} "$searched_expression" '{}' $force_multi_files ';' 2>/dev/null | sed 's|:.*$||1' | uniq
+			"${find}" . ${name_opt} "$filter_on_file" -exec "${grep}" ${base_grep_opt} ${insensitive_opt} "${searched_expression}" '{}' "${force_multi_files}" ';' 2>/dev/null | sed 's|:.*$||1' | uniq
 
 		fi
 
@@ -210,11 +214,11 @@ else
 
 		if [ $filenames_only -eq 1 ]; then
 
-			$find . -name tmp-rst -prune -o ${name_opt} "$filter_on_file" -exec $grep ${base_grep_opt} ${insensitive_opt} "$searched_expression" '{}' $force_multi_files ';' 2>/dev/null
+			"${find}" . -name tmp-rst -prune -o ${name_opt} "$filter_on_file" -exec "${grep}" ${base_grep_opt} ${insensitive_opt} "${searched_expression}" '{}' "${force_multi_files}" ';' 2>/dev/null
 
 		else
 
-			$find . -name tmp-rst -prune -o ${name_opt} "$filter_on_file" -exec $grep ${base_grep_opt} ${insensitive_opt} "$searched_expression" '{}' $force_multi_files ';' 2>/dev/null | sed 's|:.*$||1' | uniq
+			"${find}" . -name tmp-rst -prune -o ${name_opt} "$filter_on_file" -exec "${grep}" ${base_grep_opt} ${insensitive_opt} "${searched_expression}" '{}' "${force_multi_files}" ';' 2>/dev/null | sed 's|:.*$||1' | uniq
 
 		fi
 
