Symlinks better managed.

diff --git a/srm b/srm
--- a/srm
+++ b/srm
@@ -1,12 +1,12 @@
 #!/bin/sh
 
-USAGE="Usage: $(basename $0) <files to delete securely>: 'secure' rm, stores deleted files in a trash instead of deleting them directly, in order to give one more chance of retrieving them if necessary. See also: emptyTrash.sh"
+usage="Usage: $(basename $0) <files to delete securely>: 'secure' rm, stores deleted files in a trash instead of deleting them directly, in order to give one more chance of retrieving them if necessary. See also: emptyTrash.sh"
 
-TRASH_DEFAULT="$HOME/tmp/Trash"
+trash_default="$HOME/tmp/Trash"
 
 if [ -z "$TRASH" ] ; then
-	echo "Warning: \$TRASH no defined, assuming trash is $TRASH_DEFAULT"
-	TRASH="$TRASH_DEFAULT"
+	echo "Warning: \$TRASH no defined, assuming trash is $trash_default"
+	TRASH="$trash_default"
 fi
 
 
@@ -43,13 +43,15 @@ if [ -n "$*" ] ; then
 
 		fi
 
-		# File or (possibly dead) symbolic link:
+		# File/directory or (possibly dead) symbolic link:
 		if [ -e "${elem}" ] || [ -h "${elem}" ] ; then
 
 			# No need to have specific rights such as reading or writing in
 			# order to move it (no chmod needed).
 
-			if [ -e "${TRASH}/${actual_elem}" ] ; then
+			trash_target="${TRASH}/${actual_elem}"
+
+			if [ -e "${trash_target}" ] || [ -h "${trash_target}" ] ; then
 
 				new_elem="${actual_elem}-$(date +'%Y%m%d-%Hh%Mm%Ss')"
 				new_full_elem="$TRASH/${new_elem}"
@@ -73,7 +75,7 @@ if [ -n "$*" ] ; then
 
 			else
 
-				/bin/mv -f "${elem}" $TRASH
+				/bin/mv -f "${elem}" ${TRASH}
 
 			fi
 
@@ -94,7 +96,7 @@ if [ -n "$*" ] ; then
 
 else
 
-	echo "Error: no argument specified. $USAGE" 1>&2
+	echo "Error: no argument specified. $usage" 1>&2
 	exit 5
 
 fi
